name: grow_x
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+4

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  cached_network_image: ^3.3.0
  cloud_firestore: ^4.14.0
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.2
  custom_map_markers: ^0.0.2+1
  dotted_border: ^2.1.0
  dropdown_button2: ^1.8.7
  firebase_analytics:
  fast_contacts: ^3.1.3
  firebase_app_check: ^0.2.1+8
  firebase_auth: ^4.16.0
  firebase_core: ^2.14.0
  firebase_dynamic_links: ^5.4.13
  firebase_messaging: null
  firebase_storage: null
  flutter:
    sdk: flutter
  flutter_exit_app: ^1.1.2
  flutter_pdfview: ^1.3.2
  flutter_svg: ^2.0.9
  fluttertoast: null
  geoflutterfire2: ^2.3.15
  geolocator: ^10.1.0
  get: ^4.6.6
  get_storage: ^2.1.1
  google_maps_flutter: ^2.5.0
  google_sign_in: ^6.1.4
  image_picker: ^1.0.7
  intl: ^0.19.0
  lottie: ^2.7.0
  motion_tab_bar: ^2.0.4
  percent_indicator: ^4.2.3
  permission_handler: ^11.2.0
  syncfusion_flutter_pdfviewer: ^24.2.4
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Mont
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 900
    - family: play
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
          weight: 900
    - family: space
      fonts:
        - asset: assets/fonts/SpaceGrotesk-Regular.ttf
          weight: 900

flutter_assets:
  assets_path: assets/
  output_path: lib/generated/
  filename: assets.dart
  field_prefix: null
