// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBEYiGfWB9OvNx9hX1XWxfLfuRqUAO_oU',
    appId: '1:1003593022079:web:bc1f93f7bdc79056b05d4a',
    messagingSenderId: '1003593022079',
    projectId: 'growx-1081a',
    authDomain: 'growx-1081a.firebaseapp.com',
    storageBucket: 'growx-1081a.appspot.com',
    measurementId: 'G-041PECX9P3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_do8W5-ht0raEM2lWGS3fNd_aNoNikik',
    appId: '1:1003593022079:android:feac2dc570f6259db05d4a',
    messagingSenderId: '1003593022079',
    projectId: 'growx-1081a',
    storageBucket: 'growx-1081a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEMswNEm_XCtP8tJQS8DX4_czLiR2kRp0',
    appId: '1:1003593022079:ios:caf0d8b518eb35c1b05d4a',
    messagingSenderId: '1003593022079',
    projectId: 'growx-1081a',
    storageBucket: 'growx-1081a.appspot.com',
    iosBundleId: 'com.example.growx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEMswNEm_XCtP8tJQS8DX4_czLiR2kRp0',
    appId: '1:1003593022079:ios:32ad1733ee7e8a15b05d4a',
    messagingSenderId: '1003593022079',
    projectId: 'growx-1081a',
    storageBucket: 'growx-1081a.appspot.com',
    iosBundleId: 'com.example.growx.RunnerTests',
  );
}
